/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.redflix.demo.vista;

import com.redflix.demo.DemoApplication;
import com.redflix.demo.modelos.Director;
import com.redflix.demo.modelos.Pelicula;
import com.redflix.demo.modelos.RepDirector;
import com.redflix.demo.modelos.RepPelicula;
import com.redflix.demo.modelos.RepSerie;
import com.redflix.demo.modelos.RepTransmision;
import com.redflix.demo.modelos.RepUsuario;
import com.redflix.demo.modelos.Serie;
import com.redflix.demo.modelos.Usuario;
import java.awt.Component;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

/**
 *
 * @author Cesar Viasus
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    RepDirector directores;
    RepPelicula peliculas;
    RepSerie series;
    RepUsuario usuarios;
    RepTransmision transmisiones;
    String tab;

    public Ventana() {
        DemoApplication.iniciarSpring();
        directores = SpringContext.getBean(RepDirector.class);
        peliculas = SpringContext.getBean(RepPelicula.class);
        series = SpringContext.getBean(RepSerie.class);
        usuarios = SpringContext.getBean(RepUsuario.class);
        transmisiones = SpringContext.getBean(RepTransmision.class);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBGOpcionContenido = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTabEntidades = new javax.swing.JTabbedPane();
        jPanContenido = new javax.swing.JPanel();
        jPanContenidoSel = new javax.swing.JPanel();
        jRBPelicula = new javax.swing.JRadioButton();
        jRBSerie = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jTFTitulo = new javax.swing.JTextField();
        jPanPelicula = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFPelAnio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAPelResumen = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFPelDirectorNombre = new javax.swing.JTextField();
        jTFPelDirectorApellido = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanSerie = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTFSerEpisodios = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFSerTemporadas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanDirector = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTFDirNombre = new javax.swing.JTextField();
        jTFDirApellido = new javax.swing.JTextField();
        jTFDirNacionalidad = new javax.swing.JTextField();
        jTFDirPelicula = new javax.swing.JTextField();
        jPanUsuario = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTFUsuAlias = new javax.swing.JTextField();
        jTFUsuNombre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTFUsuApellido = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTFUsuEmail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jFTFUsuFecha = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        jPFUsuContrasenia = new javax.swing.JPasswordField();
        jFTFCelular = new javax.swing.JFormattedTextField();
        jButAgregar = new javax.swing.JButton();
        jButEliminar = new javax.swing.JButton();
        jButActualizar = new javax.swing.JButton();
        jButBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAEstado = new javax.swing.JTextArea();
        jCBBuscar = new javax.swing.JComboBox<>();
        jCBActualizar = new javax.swing.JComboBox<>();
        jCBEliminar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 620));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("REDFLIX");

        jTabEntidades.setName("Entidades"); // NOI18N
        jTabEntidades.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabEntidadesStateChanged(evt);
            }
        });

        jPanContenido.setName("Contenidos"); // NOI18N

        jPanContenidoSel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanContenidoSel.setName("Contenido"); // NOI18N

        jBGOpcionContenido.add(jRBPelicula);
        jRBPelicula.setSelected(true);
        jRBPelicula.setText("Pelicula");
        jRBPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPeliculaActionPerformed(evt);
            }
        });

        jBGOpcionContenido.add(jRBSerie);
        jRBSerie.setLabel("Serie");
        jRBSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBSerieActionPerformed(evt);
            }
        });

        jLabel8.setText("Titulo");

        javax.swing.GroupLayout jPanContenidoSelLayout = new javax.swing.GroupLayout(jPanContenidoSel);
        jPanContenidoSel.setLayout(jPanContenidoSelLayout);
        jPanContenidoSelLayout.setHorizontalGroup(
            jPanContenidoSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanContenidoSelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanContenidoSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBPelicula)
                    .addComponent(jRBSerie))
                .addGap(50, 50, 50)
                .addGroup(jPanContenidoSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jTFTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanContenidoSelLayout.setVerticalGroup(
            jPanContenidoSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanContenidoSelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanContenidoSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBPelicula)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanContenidoSelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRBSerie)
                    .addComponent(jTFTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanPelicula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Año");

        jTFPelAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPelAnioActionPerformed(evt);
            }
        });

        jLabel3.setText("Resumen");

        jTAPelResumen.setColumns(15);
        jTAPelResumen.setLineWrap(true);
        jTAPelResumen.setRows(5);
        jTAPelResumen.setTabSize(3);
        jScrollPane1.setViewportView(jTAPelResumen);
        jTAPelResumen.getAccessibleContext().setAccessibleDescription("");
        jTAPelResumen.getAccessibleContext().setAccessibleParent(jPanPelicula);

        jLabel6.setText("Pelicula");

        jLabel9.setText("Director");

        jTFPelDirectorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFPelDirectorNombreActionPerformed(evt);
            }
        });

        jLabel22.setText("Nombre");

        jLabel23.setText("Apellido");

        javax.swing.GroupLayout jPanPeliculaLayout = new javax.swing.GroupLayout(jPanPelicula);
        jPanPelicula.setLayout(jPanPeliculaLayout);
        jPanPeliculaLayout.setHorizontalGroup(
            jPanPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanPeliculaLayout.createSequentialGroup()
                .addGroup(jPanPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanPeliculaLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanPeliculaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(jPanPeliculaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanPeliculaLayout.createSequentialGroup()
                                .addGroup(jPanPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanPeliculaLayout.createSequentialGroup()
                                        .addGroup(jPanPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTFPelAnio, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFPelDirectorNombre))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanPeliculaLayout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addGap(71, 71, 71)))
                                .addGroup(jPanPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jTFPelDirectorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanPeliculaLayout.setVerticalGroup(
            jPanPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanPeliculaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFPelDirectorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFPelDirectorApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFPelAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanSerie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanSerie.setEnabled(false);
        jPanSerie.setPreferredSize(new java.awt.Dimension(105, 218));

        jLabel4.setText("Episodios");
        jLabel4.setEnabled(false);

        jTFSerEpisodios.setEnabled(false);

        jLabel5.setText("Temporadas");
        jLabel5.setEnabled(false);

        jTFSerTemporadas.setEnabled(false);
        jTFSerTemporadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFSerTemporadasActionPerformed(evt);
            }
        });

        jLabel7.setText("Serie");
        jLabel7.setEnabled(false);

        javax.swing.GroupLayout jPanSerieLayout = new javax.swing.GroupLayout(jPanSerie);
        jPanSerie.setLayout(jPanSerieLayout);
        jPanSerieLayout.setHorizontalGroup(
            jPanSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanSerieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(jTFSerTemporadas, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                        .addComponent(jTFSerEpisodios))
                    .addComponent(jLabel4)
                    .addGroup(jPanSerieLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanSerieLayout.setVerticalGroup(
            jPanSerieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanSerieLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFSerEpisodios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFSerTemporadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanContenidoLayout = new javax.swing.GroupLayout(jPanContenido);
        jPanContenido.setLayout(jPanContenidoLayout);
        jPanContenidoLayout.setHorizontalGroup(
            jPanContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanContenidoSel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanContenidoLayout.createSequentialGroup()
                        .addComponent(jPanPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanContenidoLayout.setVerticalGroup(
            jPanContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanContenidoSel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        jTabEntidades.addTab("Peliculas y series", jPanContenido);

        jPanDirector.setName("Directores"); // NOI18N

        jLabel10.setText("Nombre");

        jLabel11.setText("Apellido");

        jLabel12.setText("Nacionalidad");

        jLabel13.setText("Pelicula");

        jTFDirNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDirNacionalidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanDirectorLayout = new javax.swing.GroupLayout(jPanDirector);
        jPanDirector.setLayout(jPanDirectorLayout);
        jPanDirectorLayout.setHorizontalGroup(
            jPanDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanDirectorLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addComponent(jTFDirNombre)
                    .addComponent(jTFDirApellido)
                    .addComponent(jTFDirNacionalidad)
                    .addComponent(jTFDirPelicula, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanDirectorLayout.setVerticalGroup(
            jPanDirectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanDirectorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFDirNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFDirApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFDirNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFDirPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTabEntidades.addTab("Directores", jPanDirector);

        jPanUsuario.setName("Usuarios"); // NOI18N

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel14.setText("Alias");

        jTFUsuAlias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUsuAliasActionPerformed(evt);
            }
        });

        jTFUsuNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUsuNombreActionPerformed(evt);
            }
        });

        jLabel15.setText("Nombre");

        jLabel16.setText("Apellido");

        jTFUsuApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUsuApellidoActionPerformed(evt);
            }
        });

        jLabel19.setText("Campos obligatorios");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel19))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTFUsuApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(jTFUsuNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFUsuAlias, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFUsuAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFUsuNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFUsuApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setText("Email");

        jTFUsuEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFUsuEmailActionPerformed(evt);
            }
        });

        jLabel18.setText("Celular");

        jLabel20.setText("Contraseña");

        try {
            jFTFUsuFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTFUsuFecha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFTFUsuFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFTFUsuFechaActionPerformed(evt);
            }
        });

        jLabel21.setText("Fecha de nacimiento");

        jPFUsuContrasenia.setName(""); // NOI18N
        jPFUsuContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPFUsuContraseniaActionPerformed(evt);
            }
        });

        try {
            jFTFCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("### ### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jFTFCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addComponent(jPFUsuContrasenia, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTFUsuEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jFTFUsuFecha, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFUsuEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTFCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPFUsuContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTFUsuFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanUsuarioLayout = new javax.swing.GroupLayout(jPanUsuario);
        jPanUsuario.setLayout(jPanUsuarioLayout);
        jPanUsuarioLayout.setHorizontalGroup(
            jPanUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanUsuarioLayout.setVerticalGroup(
            jPanUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanUsuarioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabEntidades.addTab("Usuarios", jPanUsuario);

        jButAgregar.setLabel("Agregar");
        jButAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAgregarActionPerformed(evt);
            }
        });

        jButEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButEliminar.setLabel("Eliminar");
        jButEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEliminarActionPerformed(evt);
            }
        });

        jButActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButActualizar.setLabel("Actualizar");
        jButActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButActualizarActionPerformed(evt);
            }
        });

        jButBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButBuscar.setLabel("Buscar");
        jButBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBuscarActionPerformed(evt);
            }
        });

        jTAEstado.setEditable(false);
        jTAEstado.setBackground(new java.awt.Color(238, 238, 238));
        jTAEstado.setColumns(20);
        jTAEstado.setLineWrap(true);
        jTAEstado.setRows(5);
        jTAEstado.setWrapStyleWord(true);
        jTAEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(jTAEstado);

        jCBBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por titulo", "Por director", "por año" }));
        jCBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBBuscarActionPerformed(evt);
            }
        });

        jCBActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por titulo", "Por director" }));

        jCBEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por titulo", "Por director" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTabEntidades, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBActualizar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCBEliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButAgregar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jButActualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(jCBBuscar, javax.swing.GroupLayout.Alignment.LEADING, 0, 100, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabEntidades, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(jButBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCBEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setPanelEnabled(java.awt.Container cont, Boolean isEnabled) {
        cont.setEnabled(isEnabled);

        java.awt.Component[] components = cont.getComponents();

        for (Component component : components) {
            if (component instanceof java.awt.Container) {
                setPanelEnabled((java.awt.Container) component, isEnabled);
            }
            component.setEnabled(isEnabled);
        }
    }

    private void jRBPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPeliculaActionPerformed
        setPanelEnabled(jPanPelicula, true);
        activarPanelPelicula();
        setPanelEnabled(jPanSerie, false);
    }//GEN-LAST:event_jRBPeliculaActionPerformed

    private void jRBSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBSerieActionPerformed
        setPanelEnabled(jPanSerie, true);
       activarPanelSerie();
        setPanelEnabled(jPanPelicula, false);
    }//GEN-LAST:event_jRBSerieActionPerformed

    private void activarPanelPelicula(){
         jCBBuscar.removeAllItems();
        jCBBuscar.addItem("Por titulo");
        jCBBuscar.addItem("Por director");
        jCBBuscar.addItem("Por año");

        jCBActualizar.removeAllItems();
        jCBActualizar.addItem("Por titulo");
        jCBActualizar.addItem("Por director");

        jCBEliminar.removeAllItems();
        jCBEliminar.addItem("Por titulo");
        jCBEliminar.addItem("Por director");
    }
    
    private void activarPanelSerie(){
         jCBBuscar.removeAllItems();
        jCBBuscar.addItem("Por titulo");
        jCBBuscar.addItem("Por Temporadas");
        jCBBuscar.addItem("Por Episodios");

        jCBActualizar.removeAllItems();
        jCBActualizar.addItem("Por titulo");

        jCBEliminar.removeAllItems();
        jCBEliminar.addItem("Por titulo");
        
    }
    
    private void activarPanelDirector() {
        jCBBuscar.removeAllItems();
        jCBBuscar.addItem("Por nombre");
        jCBBuscar.addItem("Por apellido");
        jCBBuscar.addItem("Por nacionalidad");
        jCBBuscar.addItem("Por pelicula");

        jCBActualizar.removeAllItems();
        jCBActualizar.addItem("Por nombre y apellido");
        jCBActualizar.addItem("Por pelicula");

        jCBEliminar.removeAllItems();
        jCBEliminar.addItem("Por nombre y apellido");
        jCBEliminar.addItem("Por pelicula");
    }

    private void activarPanelUsuario() {

        jCBBuscar.removeAllItems();
        jCBBuscar.addItem("Por alias");
        jCBBuscar.addItem("Por nombre");
        jCBBuscar.addItem("Por apellido");
        jCBBuscar.addItem("Por Email");
        jCBBuscar.addItem("Por celular");

        jCBActualizar.removeAllItems();
        jCBActualizar.addItem("Por alias");
        jCBActualizar.addItem("Por Email");

        jCBEliminar.removeAllItems();
        jCBEliminar.addItem("Por alias");
        jCBEliminar.addItem("Por Email");

    }

    private void jTFPelAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPelAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPelAnioActionPerformed

    private void jTFSerTemporadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFSerTemporadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFSerTemporadasActionPerformed

    private void jButAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAgregarActionPerformed
        String campo = "";
        String campoAux = "";
        switch (seleccionEntidad()) {
            case "Pelicula":
                String titulo = jTFTitulo.getText();
                campo = titulo;
                String directorNombre = jTFPelDirectorNombre.getText();
                String directorApellido = jTFPelDirectorApellido.getText();
                int anio = Integer.parseInt(jTFPelAnio.getText());
                String resumen = jTAPelResumen.getText();
                Pelicula peliculaNueva = new Pelicula();
                Director directorNuevo = new Director();
                peliculaNueva.setTitulo(titulo);
                peliculaNueva.setAnio(anio);
                peliculaNueva.setResumen(resumen);
                directorNuevo.setNombre(directorNombre);
                directorNuevo.setApellido(directorApellido);
                peliculaNueva.setDirector(directorNuevo);
                break;

            case "Serie":
                titulo = jTFTitulo.getText();
                campo = titulo;
                int numTemporadas = Integer.parseInt(jTFSerTemporadas.getText());
                int numEpisodios = Integer.parseInt(jTFSerEpisodios.getText());
                Serie serieNueva = new Serie();

                serieNueva.setTitulo(titulo);
                serieNueva.setNumeroEpisodios(numEpisodios);
                serieNueva.setNumeroTemporadas(numTemporadas);
                break;
            case "Director":
                String nombre = jTFDirNombre.getText();
                campo = nombre;
                String apellido = jTFDirApellido.getText();
                campoAux = apellido;

                String nacionalidad = jTFDirNacionalidad.getText();
                String pelicula = jTFDirPelicula.getText();
                directorNuevo = new Director();

                directorNuevo.setNombre(nombre);
                directorNuevo.setApellido(apellido);
                directorNuevo.setNacionalidad(nacionalidad);
                peliculaNueva = new Pelicula();

                peliculaNueva.setTitulo(pelicula);
                directorNuevo.setPelicula(peliculaNueva);
                break;
            case "Usuario":
                String alias = jTFUsuAlias.getText();
                campo = alias;
                nombre = jTFUsuNombre.getText();
                apellido = jTFUsuApellido.getText();
                String email = jTFUsuEmail.getText();
                String celular = jFTFCelular.getText();
                String contrasena = jPFUsuContrasenia.getText();
                String fecahNac = jFTFUsuFecha.getText();

                if (alias.isEmpty() || nombre.isEmpty() || apellido.isEmpty()) {
                    campo = "Por favor rellenar los campos obligatorios.";
                } else {
                    Usuario usuarioNuevo = new Usuario();
                    usuarioNuevo.setIdAlias(alias);
                    usuarioNuevo.setNombre(nombre);
                    usuarioNuevo.setApellido(apellido);
                    usuarioNuevo.setEmail(email);
                    usuarioNuevo.setCelular(celular);
                    usuarioNuevo.setContrasena(contrasena);
                    usuarioNuevo.setFechaNaimiento(fecahNac);
                }
                break;
        }
        jTAEstado.setText(campo + campoAux + " eliminado");
        vaciarCampos();

    }//GEN-LAST:event_jButAgregarActionPerformed
    private String seleccionEntidad() {
        String entidad = "";
        if (tab.equals(jPanContenido.getName())) {
            if (jRBPelicula.isSelected()) {
                entidad = "Pelicula";
            } else {
                entidad = "Serie";
            }
        } else if (tab.equals(jPanDirector.getName())) {
            entidad = "Director";
        } else if (tab.equals(jPanUsuario.getName())) {
            entidad = "Usuario";
        }
        return entidad;
    }

    private void vaciarCampos() {
        Component[] paneles = null;
        switch (seleccionEntidad()) {
            case "Pelicula":
                paneles = jPanPelicula.getComponents();
                jTFTitulo.setText("");
                break;
            case "Serie":
                paneles = jPanSerie.getComponents();
                jTFTitulo.setText("");
                break;
            case "Director":
                paneles = jPanDirector.getComponents();
                break;
            case "Usuario":
                paneles = jPanUsuario.getComponents();
                break;
        }
        for (Component c : paneles) {
            if (c instanceof JTextField) {
                ((JTextField) c).setText("");
            } else if (c instanceof JScrollPane) {
                Component C = ((JScrollPane) c).getComponent(0);
                ((JTextArea) C).setText("");
            }
        }
    }

    private void jTFDirNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDirNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDirNacionalidadActionPerformed

    private void jTFUsuAliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuAliasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuAliasActionPerformed

    private void jTFUsuNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuNombreActionPerformed

    private void jTFUsuApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuApellidoActionPerformed

    private void jTFUsuEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFUsuEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUsuEmailActionPerformed

    private void jFTFUsuFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFTFUsuFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFTFUsuFechaActionPerformed

    private void jPFUsuContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFUsuContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPFUsuContraseniaActionPerformed

    private void jButEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEliminarActionPerformed
        int opcion = jCBEliminar.getSelectedIndex();
        String campo = "";
        String campoAux = "";
        switch (seleccionEntidad()) {
            case "Pelicula":
                switch (opcion) {
                    case 0:
                        campo = jTFTitulo.getText();
                        break;
                    case 1:
                        campo = jTFPelDirectorNombre.getText();
                        campoAux = jTFPelDirectorApellido.getText();
                        break;
                }

                break;
            case "Serie":
                campo = jTFTitulo.getText();
                break;
                              case "Director":
                switch (opcion) {
                    case 0:
                        campo = jTFDirNombre.getText();
                        campoAux = jTFDirApellido.getText();
                        break;
                    case 1:
                         campo = jTFDirPelicula.getText();
                        break;                    
                }
                break;
            case "Usuario":
                switch (opcion) {
                    case 0:
                        campo = jTFUsuAlias.getText();
                        break;
                    case 1:
                        campo = jTFUsuEmail.getText();
                        break;
                }
        }
        jTAEstado.setText(campo + campoAux + " eliminado");
        vaciarCampos();
    }//GEN-LAST:event_jButEliminarActionPerformed

    private void jButActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButActualizarActionPerformed
        int opcion = jCBActualizar.getSelectedIndex();
        String campo = "";
        String campoAux = "";
        switch (seleccionEntidad()) {
            case "Pelicula":
                switch (opcion) {
                    case 0:
                        campo = jTFTitulo.getText();
                        break;
                    case 1:
                        campo = jTFPelDirectorNombre.getText();
                        campoAux = jTFPelDirectorApellido.getText();
                        break;
                }
                break;
            case "Serie":
                campo = jTFTitulo.getText();
                break;
              case "Director":
                switch (opcion) {
                    case 0:
                        campo = jTFDirNombre.getText();
                        campoAux = jTFDirApellido.getText();
                        break;
                    case 1:
                         campo = jTFDirPelicula.getText();
                        break;                    
                }
                break;
            case "Usuario":
                switch (opcion) {
                    case 0:
                        campo = jTFUsuAlias.getText();
                        break;
                    case 1:
                        campo = jTFUsuEmail.getText();
                        break;
                }
        }
        jTAEstado.setText(campo + " Actualizado");
        vaciarCampos();
    }//GEN-LAST:event_jButActualizarActionPerformed

    private void jButBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBuscarActionPerformed
        int opcion = jCBBuscar.getSelectedIndex();
        String campo = "";
        String campoAux = "";
        switch (seleccionEntidad()) {
            case "Pelicula":
                switch (opcion) {
                    case 0:
                        campo = jTFTitulo.getText();
                        break;
                    case 1:
                        campo = jTFPelDirectorNombre.getText();
                        campoAux = jTFPelDirectorApellido.getText();
                        break;
                    case 2:
                        campo = jTFPelAnio.getText();
                        break;
                }
                break;
            case "Serie":
                switch (opcion) {
                    case 0:
                        campo = jTFTitulo.getText();
                        break;
                    case 1:
                        campo = jTFSerTemporadas.getText();
                        break;
                    case 2:
                        campo = jTFSerEpisodios.getText();
                        break;
                }
                break;
            case "Director":
                switch (opcion) {
                    case 0:
                        campo = jTFDirNombre.getText();
                        break;
                    case 1:
                        campo = jTFDirApellido.getText();
                        break;
                    case 2:
                        campo = jTFDirNacionalidad.getText();
                        break;
                    case 3:
                        campo = jTFDirPelicula.getText();
                        break;
                }
                break;
            case "Usuario":
                switch (opcion) {
                    case 0:
                        campo = jTFUsuAlias.getText();
                        break;
                    case 1:
                        campo = jTFUsuNombre.getText();
                        break;
                    case 2:
                        campo = jTFUsuApellido.getText();
                        break;
                    case 3:
                        campo = jTFUsuEmail.getText();
                        break;
                    case 4:
                        campo = jFTFCelular.getText();
                        break;
                }
                break;
        }
        jTAEstado.setText(campo + campoAux + " buscado");
        vaciarCampos();
    }//GEN-LAST:event_jButBuscarActionPerformed

    private void jTFPelDirectorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFPelDirectorNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFPelDirectorNombreActionPerformed

    private void jCBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBBuscarActionPerformed

    private void jTabEntidadesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabEntidadesStateChanged
        tab = jTabEntidades.getSelectedComponent().getName();
        switch (tab) {
            case "Contenidos":
                activarPanelPelicula();
                setPanelEnabled(jPanPelicula, true);
                setPanelEnabled(jPanSerie, false);
                break;
            case "Directores":
                activarPanelDirector();
                break;
            case "Usuarios":
                activarPanelUsuario();
        }
    }//GEN-LAST:event_jTabEntidadesStateChanged

    // public void  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ventana().setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jBGOpcionContenido;
    private javax.swing.JButton jButActualizar;
    private javax.swing.JButton jButAgregar;
    private javax.swing.JButton jButBuscar;
    private javax.swing.JButton jButEliminar;
    private javax.swing.JComboBox<String> jCBActualizar;
    private javax.swing.JComboBox<String> jCBBuscar;
    private javax.swing.JComboBox<String> jCBEliminar;
    private javax.swing.JFormattedTextField jFTFCelular;
    private javax.swing.JFormattedTextField jFTFUsuFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPFUsuContrasenia;
    private javax.swing.JPanel jPanContenido;
    private javax.swing.JPanel jPanContenidoSel;
    private javax.swing.JPanel jPanDirector;
    private javax.swing.JPanel jPanPelicula;
    private javax.swing.JPanel jPanSerie;
    private javax.swing.JPanel jPanUsuario;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRBPelicula;
    private javax.swing.JRadioButton jRBSerie;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTAEstado;
    private javax.swing.JTextArea jTAPelResumen;
    private javax.swing.JTextField jTFDirApellido;
    private javax.swing.JTextField jTFDirNacionalidad;
    private javax.swing.JTextField jTFDirNombre;
    private javax.swing.JTextField jTFDirPelicula;
    private javax.swing.JTextField jTFPelAnio;
    private javax.swing.JTextField jTFPelDirectorApellido;
    private javax.swing.JTextField jTFPelDirectorNombre;
    private javax.swing.JTextField jTFSerEpisodios;
    private javax.swing.JTextField jTFSerTemporadas;
    private javax.swing.JTextField jTFTitulo;
    private javax.swing.JTextField jTFUsuAlias;
    private javax.swing.JTextField jTFUsuApellido;
    private javax.swing.JTextField jTFUsuEmail;
    private javax.swing.JTextField jTFUsuNombre;
    private javax.swing.JTabbedPane jTabEntidades;
    // End of variables declaration//GEN-END:variables
}
